name: Release
on:
  push:
    tags:
      - "*-*-*-*"
jobs:
  build_win:
    runs-on: windows-2022
    steps:
    - name: "Clone source"
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: "Setup msvc"
      uses: ilammy/msvc-dev-cmd@v1
    - name: "Download Qt5"
      shell: bash
      run: |
        curl --output C:/qt5.7z -L "https://github.com/LoL-Fantome/lolcustomskin-tools/releases/download/release23/qt5.15.13-x86_64-msvc-static.7z"
        sha256sum C:/qt5.7z
        7z x -oC:/ C:/qt5.7z
    - name: "Build"
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" "-DCMAKE_PREFIX_PATH:PATH=C:/qt5.15.13-x86_64-msvc-static" "-DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreaded" "-DCMAKE_BUILD_TYPE:STRING=Release" ..
        cmake --build .
    - name: "Package"
      shell: bash
      run: |
        ./make-release.sh build
        7z a cslol-manager-windows.exe -sfx7z.sfx cslol-manager/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: cslol-manager-windows
        path: cslol-manager-windows.exe
        retention-days: 15
  build_mac:
    runs-on: macos-12
    steps:
    - name: "Clone source"
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: "Download Qt5"
      run: |
        curl --output qt5.tar.xz -L "https://github.com/LeagueToolkit/cslol-manager/releases/download/release23/qt5.15.13-x86_64-macos-static.tar.xz"
        shasum -a 256 qt5.tar.xz
        tar xf qt5.tar.xz --strip-components 2 -C $HOME
    - name: "Build"
      run: |
        cmake -DCMAKE_PREFIX_PATH=$HOME/qt5.15.13-x86_64-macos-static -DCMAKE_BUILD_TYPE=Release -B build -S .
        cmake --build build
    - name: "Package"
      shell: bash
      run: |
        ./make-release-mac.sh "build" "cslol-manager-macos"
        tar caf cslol-manager-macos.tar.xz cslol-manager-macos/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: cslol-manager-macos
        path: cslol-manager-macos.tar.xz
        retention-days: 15
  release:
    needs: [build_win, build_mac]
    runs-on: ubuntu-22.04
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        failOnError: 'true'
        commitMode: 'true'
        toTag: ${{ github.ref_name }}
        configurationJson: |
            {
              "tag_resolver": {
                "method": "sort",
                "filter": {
                  "pattern": "\\d+-\\d+-\\d+-.+",
                  "flags": "gu"
                }
              },
              "pr_template": "- #{{MERGE_SHA}}: #{{TITLE}}",
              "template": "#{{UNCATEGORIZED}}"
            }
        ignorePreReleases: ${{ endsWith(github.ref_name, '-prerelease') || endsWith(github.ref_name, '-test') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Release"
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
        prerelease: ${{ endsWith(github.ref_name, '-prerelease') || endsWith(github.ref_name, '-test') }}
        body: ${{ steps.github_release.outputs.changelog }}
